server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appointment_db
    username: postgres
    password: Mthobisi@123

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true

  liquibase:
    change-log: classpath:changelog/db.changelog-master.yaml
